# Generated by Django 6.0.2 on 2026-02-27 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_product_description'),
        ('variant', '0002_alter_variant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='product.product')),
            ],
            options={
                'unique_together': {('product', 'sku_code')},
            },
        ),
        migrations.CreateModel(
            name='ProductSKUOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_options', to='prd_variant.productsku')),
                ('variant_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.variantoption')),
            ],
            options={
                'unique_together': {('sku', 'variant_option')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_options', to='product.product')),
                ('variant_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.variantoption')),
            ],
            options={
                'unique_together': {('product', 'variant_option')},
            },
        ),
    ]
