# Generated by Django 6.0.2 on 2026-03-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd_variant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='low_stock_threshold',
            field=models.IntegerField(default=5),
        ),
    ]
