# Generated by Django 6.0.2 on 2026-03-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd_variant', '0002_productsku_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productsku',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productsku',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productsku',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=10, null=True),
        ),
    ]
