# Generated by Django 6.0.2 on 2026-04-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd_variant', '0003_productsku_height_productsku_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Height in cm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Length in cm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in kg', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Width in cm', max_digits=10),
        ),
    ]
