# Generated by Django 6.0.2 on 2026-05-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd_variant', '0004_alter_productsku_height_alter_productsku_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Height in IN', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Length in IN', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in LBS', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Width in IN', max_digits=10),
        ),
    ]
