# Generated by Django 6.0.2 on 2026-02-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, max_length=750),
        ),
    ]
