# Generated by Django 6.0.2 on 2026-02-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_type',
            field=models.CharField(choices=[('product', 'Product'), ('default_card', 'Default Card'), ('multi_level_cat', 'Multi-Level Category'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
