# Generated by Django 6.0.2 on 2026-03-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_category_display_type_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_type',
            field=models.CharField(choices=[('product_card', 'Product Card'), ('default_card', 'Default Card'), ('multi_level_cat', 'Multi-Level Category'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
