# Generated by Django 6.0.2 on 2026-04-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathogenPanelLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathogen_target', models.CharField(max_length=255, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('panel_count', models.PositiveIntegerField(default=0)),
                ('panels', models.JSONField(blank=True, default=list)),
                ('source_sheet', models.CharField(default='Pathogen Panel Lookup', max_length=100)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pathogen Panel Lookup',
                'verbose_name_plural': 'Pathogen Panel Lookup',
                'ordering': ['pathogen_target'],
                'indexes': [models.Index(fields=['is_active', 'normalized_name'], name='chatbot_pat_is_acti_99ff49_idx')],
            },
        ),
    ]
