# Generated by Django 6.0.2 on 2026-06-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_pathogenpanellookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='doc_type',
            field=models.CharField(choices=[('products', 'Products'), ('company', 'Company'), ('faq', 'FAQ'), ('policies', 'Policies'), ('service', 'Service'), ('other', 'Other')], default='other', help_text='Category of this knowledge base entry.', max_length=100),
        ),
    ]
