# Generated by Django 6.0.2 on 2026-03-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25, unique=True)),
                ('code', models.CharField(db_index=True, help_text=' user enters this', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_count', models.PositiveIntegerField(default=0, help_text='max allowed uses (0 = unlimited)')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='how many times used so far')),
                ('per_user_limit', models.PositiveIntegerField(default=1, help_text='how many times one user can use')),
                ('min_price', models.DecimalField(decimal_places=2, default=0.0, help_text='cart must be at least', max_digits=10)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='cart must be at most', max_digits=10, null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text="10 = '10%'  or $10", max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
