# Generated by Django 6.0.2 on 2026-03-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(),
        ),
    ]
