# Generated by Django 6.0.2 on 2026-03-04 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_payment_method'),
        ('variant', '0005_remove_variant_unique_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_option_name', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_variants', to='order.order')),
                ('variant_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.variantoption')),
            ],
        ),
    ]
