# Generated by Django 6.0.2 on 2026-04-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_coupon_amt_order_coupon_code_order_coupon_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_label_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_service_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_service_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='ups_shipment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
