# Generated by Django 6.0.2 on 2026-04-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_shipment_created_at_order_shipping_label_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_state_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
