# Generated by Django 6.0.2 on 2026-04-14 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_billing_state_code_order_shipping_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordervariants',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orderItems_variants', to='order.orderitem'),
            preserve_default=False,
        ),
    ]
