# Generated by Django 6.0.2 on 2026-04-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_ordervariants_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sku_code',
            field=models.CharField(default='sku', max_length=500),
            preserve_default=False,
        ),
    ]
