# Generated by Django 6.0.2 on 2026-04-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_paymet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='return_rejected_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_requested_reason',
            field=models.TextField(blank=True),
        ),
    ]
