# Generated by Django 6.0.2 on 2026-04-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_refund_amt_order_return_rejected_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(choices=[('none', 'None'), ('return_requested', 'Return Requested'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected')], default='none', max_length=20),
        ),
    ]
