# Generated by Django 6.0.2 on 2026-04-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_ups_last_event_at_order_ups_last_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipment_created_at',
            new_name='label_created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_label_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_service_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_service_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ups_shipment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(default='UPS', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_status',
            field=models.CharField(default='label_created', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_label',
            field=models.ImageField(blank=True, null=True, upload_to='shipping_labels/'),
        ),
        migrations.AddField(
            model_name='order',
            name='ups_transaction_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
