# Generated by Django 6.0.2 on 2026-04-25 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_rename_shipment_created_at_order_label_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='return_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('partially_shipped', 'Partially Shipped'), ('shipped', 'Shipped'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('partially_returned', 'Partially Returned'), ('returned', 'Returned'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatusupdate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('partially_shipped', 'Partially Shipped'), ('shipped', 'Shipped'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('partially_returned', 'Partially Returned'), ('returned', 'Returned'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=20),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(choices=[('outbound', 'Outbound'), ('return', 'Return')], default='outbound', max_length=10)),
                ('status', models.CharField(choices=[('label_created', 'Label Created'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='label_created', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=30, null=True)),
                ('shipment_id', models.CharField(blank=True, max_length=30, null=True)),
                ('carrier', models.CharField(default='UPS', max_length=10)),
                ('ups_transaction_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_label', models.ImageField(blank=True, null=True, upload_to='shipping_labels/')),
                ('label_created_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True, null=True)),
                ('return_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, related_name='shipments', to='order.orderitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='order.order')),
                ('return_initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_returns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
