# Generated by Django 6.0.2 on 2026-04-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_refund_amount_order_refund_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('partially_shipped', 'Partially Shipped'), ('shipped', 'Shipped'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered'), ('return_initiate', 'Return initiated'), ('partially_returned', 'Partially Returned'), ('returned', 'Returned'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatusupdate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('partially_shipped', 'Partially Shipped'), ('shipped', 'Shipped'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered'), ('return_initiate', 'Return initiated'), ('partially_returned', 'Partially Returned'), ('returned', 'Returned'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=20),
        ),
    ]
