# Generated by Django 6.0.2 on 2026-04-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_status_alter_orderstatusupdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancel_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
