# Generated by Django 6.0.2 on 2026-04-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_remove_order_cancel_notes_remove_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_partially_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
