# Generated by Django 6.0.2 on 2026-04-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_order_is_partially_refunded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='return_status',
        ),
    ]
