# Generated by Django 6.0.2 on 2026-04-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_remove_orderitem_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_status',
            field=models.CharField(choices=[('none', 'No Return'), ('initiated', 'Return Initiated'), ('returned', 'Returned')], default='none', max_length=20),
        ),
    ]
