# Generated by Django 6.0.2 on 2026-05-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_orderitem_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('none', 'None'), ('issued', 'Issued'), ('declined', 'Declined')], default='none', max_length=20),
        ),
    ]
