# Generated by Django 6.0.2 on 2026-05-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_alter_order_status_alter_orderstatusupdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Height in IN', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Length in IN', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in LBS', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Width in IN', max_digits=10),
        ),
    ]
