# Generated by Django 6.0.2 on 2026-05-14 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_orderitem_dimensions'),
        ('order', '0029_orderitem_height_orderitem_length_orderitem_weight_and_more'),
    ]

    operations = [
    ]
