# Generated by Django 6.0.6 on 2026-06-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_merge_20260514_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Height in IN', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Length in IN', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in LBS', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Width in IN', max_digits=10),
        ),
    ]
