# Generated by Django 6.0.2 on 2026-02-27 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_category_display_type_category_url'),
        ('variant', '0002_alter_variant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='category.category'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_variant'),
        ),
    ]
