# Generated by Django 6.0.2 on 2026-02-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0003_variant_category_variant_unique_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
