# Generated by Django 6.0.2 on 2026-02-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_category_display_type_category_url'),
        ('variant', '0004_alter_variant_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='variant',
            name='unique_variant',
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category', 'name'), name='unique_variant_per_category'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('name',), name='unique_variant_no_category'),
        ),
    ]
