# Generated by Django 6.0.2 on 2026-03-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0005_remove_variant_unique_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
