# Generated by Django 6.0.2 on 2026-03-04 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_sku_code_cartvariants'),
        ('variant', '0005_remove_variant_unique_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartvariants',
            name='variant_option_id',
        ),
        migrations.AddField(
            model_name='cartvariants',
            name='variant_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='variant.variantoption'),
            preserve_default=False,
        ),
    ]
