# Generated by Django 6.0.2 on 2026-03-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartvariants_variant_option_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='has_variants',
            field=models.BooleanField(default=False),
        ),
    ]
