# Generated by Django 6.0.2 on 2026-03-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_has_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
