# Generated by Django 6.0.2 on 2026-03-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_copon_amt_cart_coupon_code_alter_cart_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='copon_amt',
            new_name='copon_val',
        ),
    ]
