# Generated by Django 6.0.2 on 2026-03-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_rename_copon_amt_cart_copon_val'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='copon_val',
            new_name='coupon_val',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
