# Generated by Django 6.0.2 on 2026-04-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_rename_copon_val_cart_coupon_val_cart_coupon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_customizable',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
