# Generated by Django 6.0.2 on 2026-04-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_cart_is_customizable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_amt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
