# Generated by Django 6.0.2 on 2026-02-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QBConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='QB Access Token (auto-refreshed)')),
                ('refresh_token', models.TextField(help_text='QB Refresh Token (rotates every 100 days)')),
                ('realm_id', models.CharField(help_text='QB Company ID', max_length=100)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'QuickBooks Config',
                'verbose_name_plural': 'QuickBooks Config',
            },
        ),
    ]
