# Generated by Django 6.0.2 on 2026-04-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_taxconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Store Name', max_length=255)),
                ('street', models.CharField(default='120 Dewey Drive', max_length=255)),
                ('state', models.CharField(default='KY', max_length=10)),
                ('country', models.CharField(default='US', max_length=10)),
                ('city', models.CharField(default='Nicholasville', max_length=100)),
                ('zip', models.CharField(default='40356', max_length=20)),
            ],
        ),
    ]
