# Generated by Django 6.0.2 on 2026-04-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_upsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='upsconfig',
            name='account_num',
            field=models.CharField(default='40356', max_length=20),
        ),
    ]
