# Generated by Django 6.0.2 on 2026-04-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_upsconfig_account_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upsconfig',
            name='street',
            field=models.TextField(),
        ),
    ]
