# Generated by Django 6.0.2 on 2026-05-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_upsconfig_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='upsconfig',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
