# Generated by Django 6.0.2 on 2026-02-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0006_category_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('type', models.CharField(choices=[('default', 'Default'), ('product_cat', 'Product Categories')], default='default', max_length=20)),
                ('hide_menu_items', models.BooleanField(default=True)),
                ('navigation_flag', models.BooleanField(default=False)),
                ('category', models.ForeignKey(limit_choices_to={'parent': None}, on_delete=django.db.models.deletion.CASCADE, related_name='header_menus', to='category.category')),
            ],
        ),
    ]
