# Generated by Django 6.0.2 on 2026-02-24 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_sort_order'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headermenus',
            name='category',
            field=models.ForeignKey(limit_choices_to={'parent': None}, on_delete=django.db.models.deletion.CASCADE, related_name='header_categories', to='category.category'),
        ),
    ]
