# Generated by Django 6.0.2 on 2026-03-23 18:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_careeropenrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeropenrole',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careeropenrole',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careeropenrole',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careeropenrole',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='careeropenrole',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careeropenrole',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('linkedin_url', models.URLField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('resume', models.FileField(max_length=500, upload_to='careers/resumes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='home.careeropenrole')),
            ],
            options={
                'verbose_name': 'Career Application',
                'verbose_name_plural': 'Career Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
