# Generated by Django 6.0.2 on 2026-03-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_careeropenrole_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('start_date', models.DateField()),
                ('count', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
