# Generated by Django 6.0.2 on 2026-03-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='start_date',
            new_name='date',
        ),
    ]
