# Generated by Django 6.0.2 on 2026-03-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_start_date_search_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
