# Generated by Django 6.0.2 on 2026-03-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_search_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Type',
                'verbose_name_plural': 'Landing Page Types',
                'ordering': ['created_at'],
            },
        ),
    ]
