# Generated by Django 6.0.2 on 2026-03-30 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_landingpagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('btn_text', models.CharField(blank=True, max_length=100)),
                ('btn_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landing_page_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='home.landingpagetype')),
            ],
            options={
                'verbose_name': 'Landing Page Context',
                'verbose_name_plural': 'Landing Page Contexts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landing_page_images/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landing_page_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.landingpagetype')),
            ],
            options={
                'verbose_name': 'Landing Page Image',
                'verbose_name_plural': 'Landing Page Images',
                'ordering': ['created_at'],
            },
        ),
    ]
