# Generated by Django 6.0.2 on 2026-03-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_landingpagecontext_landingpageimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpagecontext',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='landingpagecontext',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpagecontext',
            name='title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landingpageimage',
            name='image',
            field=models.ImageField(help_text='Recommended dimensions for Herosection : 1920×900px, Other sections 1200×800px', upload_to='landing_page_images/'),
        ),
    ]
