# Generated by Django 6.0.2 on 2026-05-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_text_landingpagecontext_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontext',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="10 = '10%'", max_digits=10),
        ),
        migrations.AddField(
            model_name='landingpagecontext',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontext',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
