# Generated by Django 6.0.2 on 2026-05-14 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_landingpagecontext_discount_value_and_more'),
        ('product', '0033_alter_productrelatedinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_page_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='home.landingpagecontext')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_products', to='product.product')),
            ],
            options={
                'unique_together': {('landing_page_context', 'product')},
            },
        ),
    ]
