# Generated by Django 6.0.6 on 2026-06-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_blogpostimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostimage',
            name='show_in_gallery',
            field=models.BooleanField(default=False, help_text='Check to display this image at the bottom of the blog post.'),
        ),
    ]
