# Generated by Django 6.0.2 on 2026-02-15 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('role', models.CharField(choices=[('superadmin', 'superadmin'), ('customer', 'customer')], db_index=True, max_length=32)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('Company_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('Street_Address', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('Address_Line_2', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('Town_City', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('Zip_Code', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'indexes': [models.Index(fields=['email'], name='users_custo_email_c80f75_idx'), models.Index(fields=['role'], name='users_custo_role_6a37b1_idx')],
            },
        ),
    ]
