# Generated by Django 6.0.2 on 2026-02-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_roles_userrole'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_role_6a37b1_idx',
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role'], name='users_userr_user_id_595a92_idx'),
        ),
        migrations.AlterModelTable(
            name='roles',
            table='users_roles',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='users_userrole',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.UserRole', to='users.roles'),
        ),
    ]
