# Generated by Django 6.0.2 on 2026-02-17 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('users', '0003_remove_customuser_users_custo_role_6a37b1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_users', to='country.state'),
        ),
    ]
