# Generated by Django 6.0.2 on 2026-02-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
