# Generated by Django 6.0.2 on 2026-02-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userrole_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
