# Generated by Django 6.0.2 on 2026-03-27 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
