# Generated by Django 6.0.2 on 2026-03-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active_uid',
        ),
    ]
