# Generated by Django 6.0.2 on 2026-03-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_active_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active_uid',
        ),
    ]
