# Generated by Django 6.0.2 on 2026-03-27 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customuser_active_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
