# Generated by Django 6.0.2 on 2026-04-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_description_productfaq_answer_and_more'),
        ('users', '0015_usertypes_customerproductprices'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customerproductprices',
            constraint=models.UniqueConstraint(fields=('user', 'product', 'user_type'), name='unique_customer_product_price'),
        ),
    ]
