# Generated by Django 6.0.2 on 2026-04-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_description_productfaq_answer_and_more'),
        ('users', '0016_customerproductprices_unique_customer_product_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerproductprices',
            name='unique_customer_product_price',
        ),
        migrations.AddConstraint(
            model_name='customerproductprices',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_customer_product_price'),
        ),
    ]
