# Generated by Django 6.0.2 on 2026-04-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_description_productfaq_answer_and_more'),
        ('users', '0017_remove_customerproductprices_unique_customer_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerproductprices',
            name='unique_customer_product_price',
        ),
        migrations.RemoveIndex(
            model_name='customerproductprices',
            name='users_custo_user_id_633700_idx',
        ),
        migrations.AddIndex(
            model_name='customerproductprices',
            index=models.Index(fields=['user_type', 'product'], name='users_custo_user_ty_e9fa17_idx'),
        ),
    ]
