# Generated by Django 6.0.2 on 2026-04-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_customerproductprices_unique_customer_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproductprices',
            name='user',
        ),
    ]
