# Generated by Django 6.0.2 on 2026-04-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_customerproductprices_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertypes',
            name='price',
        ),
        migrations.AddField(
            model_name='customerproductprices',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
