# Generated by Django 6.0.2 on 2026-04-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_description_productfaq_answer_and_more'),
        ('users', '0020_remove_usertypes_price_customerproductprices_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customerproductprices',
            constraint=models.UniqueConstraint(fields=('user_type', 'product'), name='unique_customer_product_price'),
        ),
    ]
