# Generated by Django 6.0.2 on 2026-04-05 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_customerproductprices_unique_customer_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.usertypes'),
        ),
    ]
