# Generated by Django 6.0.2 on 2026-04-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_customuser_laboratory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='laboratory',
        ),
    ]
