# Generated by Django 6.0.2 on 2026-04-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_customuser_laboratory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Laboratories',
                'db_table': 'users_Laboratories',
            },
        ),
        migrations.RemoveField(
            model_name='usertypes',
            name='is_displayed',
        ),
    ]
