# Generated by Django 6.0.2 on 2026-04-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_laboratory_remove_usertypes_is_displayed'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerproductprices',
            name='unique_customer_product_price',
        ),
        migrations.RemoveIndex(
            model_name='customerproductprices',
            name='users_custo_user_ty_e9fa17_idx',
        ),
        migrations.AlterModelTable(
            name='customerproductprices',
            table=None,
        ),
        migrations.RemoveField(
            model_name='customerproductprices',
            name='user_type',
        ),
    ]
