# Generated by Django 6.0.2 on 2026-04-09 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_customuser_laboratory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproductprices',
            name='laboratory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_product_prices', to='users.laboratory'),
            preserve_default=False,
        ),
    ]
