# Generated by Django 6.0.2 on 2026-04-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_description_productfaq_answer_and_more'),
        ('users', '0027_customerproductprices_laboratory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerproductprices',
            index=models.Index(fields=['laboratory', 'product'], name='laboratory__laborat_514f35_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerproductprices',
            constraint=models.UniqueConstraint(fields=('laboratory', 'product'), name='unique_laboratory_product_price'),
        ),
        migrations.AlterModelTable(
            name='customerproductprices',
            table='laboratory_product_prices',
        ),
    ]
