# Generated by Django 6.0.2 on 2026-04-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_customerproductprices_laboratory__laborat_514f35_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customerproductprices',
            name='laboratory__laborat_514f35_idx',
        ),
        migrations.RemoveConstraint(
            model_name='customerproductprices',
            name='unique_laboratory_product_price',
        ),
        migrations.DeleteModel(
            name='CustomerProductPrices',
        ),
    ]
