# Generated by Django 6.0.2 on 2026-04-09 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_description_productfaq_answer_and_more'),
        ('users', '0029_remove_customerproductprices_laboratory__laborat_514f35_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizableProductprices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_product_prices', to='users.laboratory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizable_product_prices', to='product.product')),
            ],
            options={
                'db_table': 'customizabel_laboratory_product_prices',
            },
        ),
    ]
