# Generated by Django 6.0.2 on 2026-04-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_description_productfaq_answer_and_more'),
        ('users', '0030_customizableproductprices'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customizableproductprices',
            index=models.Index(fields=['laboratory', 'product'], name='customizabe_laborat_31e00a_idx'),
        ),
        migrations.AddConstraint(
            model_name='customizableproductprices',
            constraint=models.UniqueConstraint(fields=('laboratory', 'product'), name='unique_laboratory_product_price'),
        ),
    ]
