# Generated by Django 6.0.2 on 2026-04-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_repair_customuser_laboratory_fk'),
        ('users', '0031_customizableproductprices_customizabe_laborat_31e00a_idx_and_more'),
    ]

    operations = [
    ]
