# Generated by Django 6.0.2 on 2026-04-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_merge_20260414_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='quickbook_customer_id',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
