"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from config.settings import configSettings
# from config.logging_config import  LOGGING

from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-5w2+z9e0!(jhtim!i1#ob$4%bo8cv4-p$m3j-52f!p#((z07gq')

DEBUG = os.getenv('DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    "corsheaders",
    "django_celery_beat",  
    'users.apps.UsersConfig',
    'country.apps.CountryConfig',
    'category.apps.CategoryConfig',
    'product.apps.ProductConfig',
    'cart.apps.CartConfig',
    'shipping.apps.ShippingConfig',
    'order.apps.OrderConfig',
    'payments.apps.PaymentsConfig',
    'home.apps.HomeConfig',
    'variant.apps.VariantConfig',
    'prd_variant.apps.PrdVariantConfig',
    'documet.apps.DocumetConfig',
    'coupon.apps.CouponConfig',
    'settings.apps.SettingsConfig',
    'comment.apps.CommentConfig',





    'chatbot.apps.ChatbotConfig',
]


AUTH_USER_MODEL = 'users.CustomUser'


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'biopathproj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'biopathproj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {

        'ENGINE': 'django.db.backends.mysql',
        'CONN_MAX_AGE': 60,
        'NAME': 'Biopathogenix',
        'USER': 'myuser',
        'PASSWORD': 'MySecurePass123!',
        'HOST': '40.90.193.137',   # <-- Your VM's IP address
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}



CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    "https://biopathogenix.com",
    "https://bio.biopathogenix.com",
]
# CORS_ALLOW_CREDENTIALS = True





# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND","django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.office365.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"  # True/False as string in env
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False") == "True"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "noreply@biopathogenix.com")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "Ras05143")  # set this in env
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
CAREERS_RECIPIENT_EMAIL = os.environ.get("CAREERS_RECIPIENT_EMAIL", "careers@biopathogenix.com")
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", 20))
WELCOME_LOGO_URL = os.environ.get("WELCOME_LOGO_URL","http://localhost:3000/images/logo/BioPathogenix-Horizontal-1.svg")
# Guard against enabling both TLS and SSL at the same time.
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    EMAIL_USE_SSL = False

GRAPH_TENANT_ID = os.environ.get("GRAPH_TENANT_ID", "")
GRAPH_CLIENT_ID = os.environ.get("GRAPH_CLIENT_ID", "")
GRAPH_CLIENT_SECRET = os.environ.get("GRAPH_CLIENT_SECRET", "")
GRAPH_SCOPE = os.environ.get("GRAPH_SCOPE", "https://graph.microsoft.com/.default")
GRAPH_API_BASE = os.environ.get("GRAPH_API_BASE", "https://graph.microsoft.com/v1.0")
GRAPH_SENDER = os.environ.get("GRAPH_SENDER", DEFAULT_FROM_EMAIL)
GRAPH_ENABLED = all([GRAPH_TENANT_ID, GRAPH_CLIENT_ID, GRAPH_CLIENT_SECRET, GRAPH_SENDER])

# TaxJar configuration
TAXJAR_API_KEY = os.environ.get("TAXJAR_API_KEY", "")
TAXJAR_USE_SANDBOX = os.environ.get("TAXJAR_USE_SANDBOX", "true").lower() == "true"
TAXJAR_API_BASE = "https://api.sandbox.taxjar.com" if TAXJAR_USE_SANDBOX else "https://api.taxjar.com"
TAX_NEXUS_COUNTRY = os.environ.get("TAX_NEXUS_COUNTRY", "US")
TAX_NEXUS_ZIP = os.environ.get("TAX_NEXUS_ZIP", "40356")
TAX_NEXUS_STATE = os.environ.get("TAX_NEXUS_STATE", "KY")
TAX_NEXUS_CITY = os.environ.get("TAX_NEXUS_CITY", "Nicholasville")
TAX_NEXUS_STREET = os.environ.get("TAX_NEXUS_STREET", "120 Dewey Drive")

CELERY_BROKER_URL         = os.getenv("REDIS_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND     = os.getenv("REDIS_URL", default="redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT     = ["json"]
CELERY_TASK_SERIALIZER    = "json"
CELERY_RESULT_SERIALIZER  = "json"
CELERY_TIMEZONE           = "UTC"
USE_I18N = True
TIME_ZONE = os.getenv('TIME_ZONE', 'UTC')
USE_TZ = True
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

USE_REDIS_CACHE = os.getenv("USE_REDIS_CACHE", "false").lower() == "true"

from celery.schedules import crontab
 
CELERY_BEAT_SCHEDULE = {
    "ups-poll-every-30-min": {
    "task":     "order.poll_all_active_orders",
        "schedule": crontab(minute="*/1"),  # every 30 minutes
    },
}


if USE_REDIS_CACHE:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": os.getenv("REDIS_URL", default="redis://localhost:6379/0"),
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "local-dev-cache",
        }
    }

# ── Celery configuration ──────────────────────────────────────────────────────

 
# ── Celery Beat — periodic task schedule ─────────────────────────────────────


# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles' 
# # STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Add this
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]



MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=3600), 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 5,
}



DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB or more
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760
IMPORT_EXPORT_USE_TRANSACTIONS = True

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '150/min',
        'login': '10/min',      # used by custom throttle if you define scope 'login'
    }
}

