# Generated by Django 6.0.2 on 2026-02-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_product_pro_categor_01a4d5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
