# Generated by Django 6.0.2 on 2026-02-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_has_variants_product_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='links',
            field=models.TextField(blank=True),
        ),
    ]
