# Generated by Django 6.0.2 on 2026-02-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, help_text='you allowed to write upto 500 characters', max_length=500),
        ),
    ]
