# Generated by Django 6.0.2 on 2026-02-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
