# Generated by Django 6.0.2 on 2026-03-02 19:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd_variant', '0002_productsku_low_stock_threshold'),
        ('product', '0008_alter_product_has_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('ifu', 'Information for Use'), ('sds', 'Safety Data Sheet(s)'), ('other', 'Other Documents')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(db_column='file_url', max_length=500, upload_to='product_docs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='product.product')),
                ('sku', models.ForeignKey(blank=True, help_text='Optional: assign to a specific SKU/variant combination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='prd_variant.productsku')),
            ],
            options={
                'verbose_name': 'Product Document',
                'verbose_name_plural': 'Product Documents',
                'ordering': ['section', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['product', 'is_active', 'section', 'sort_order'], name='product_pro_product_7d6310_idx'), models.Index(fields=['sku', 'is_active'], name='product_pro_sku_id_4d83fc_idx')],
            },
        ),
    ]
