# Generated by Django 6.0.2 on 2026-03-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='hover',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
