# Generated by Django 6.0.2 on 2026-03-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productimage_hover'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_customizable',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
