# Generated by Django 6.0.2 on 2026-03-10 07:56

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_is_customizable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trademark',
            field=models.JSONField(blank=True, default=product.models.trademark_default, help_text='Position value should be pre/post ,if the product has trademark mark checked as True '),
        ),
    ]
