# Generated by Django 6.0.2 on 2026-03-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd_variant', '0003_productsku_height_productsku_length_and_more'),
        ('product', '0012_product_trademark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdocument',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Product Document', 'verbose_name_plural': 'Product Documents'},
        ),
        migrations.RemoveIndex(
            model_name='productdocument',
            name='product_pro_product_7d6310_idx',
        ),
        migrations.AddIndex(
            model_name='productdocument',
            index=models.Index(fields=['product', 'is_active', 'sort_order'], name='product_pro_product_234df7_idx'),
        ),
        migrations.RemoveField(
            model_name='productdocument',
            name='section',
        ),
    ]
