# Generated by Django 6.0.2 on 2026-03-10 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documet', '0001_initial'),
        ('product', '0013_alter_productdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdocument',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prd_documents', to='documet.documenttype'),
            preserve_default=False,
        ),
    ]
