# Generated by Django 6.0.2 on 2026-03-11 01:22

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documet', '0001_initial'),
        ('prd_variant', '0003_productsku_height_productsku_length_and_more'),
        ('product', '0014_productdocument_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdocument',
            options={'ordering': ['section', 'sort_order', 'id'], 'verbose_name': 'Product Document', 'verbose_name_plural': 'Product Documents'},
        ),
        migrations.RemoveIndex(
            model_name='productdocument',
            name='product_pro_product_234df7_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='trademark',
            field=models.JSONField(blank=True, default=product.models.trademark_default, help_text='Position value should be pre/post ,if the product has trademark mark display as True '),
        ),
        migrations.AddIndex(
            model_name='productdocument',
            index=models.Index(fields=['product', 'is_active', 'section', 'sort_order'], name='product_pro_product_1ba86c_idx'),
        ),
    ]
