# Generated by Django 6.0.2 on 2026-03-11 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_productdocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='trademark',
        ),
    ]
