# Generated by Django 6.0.2 on 2026-03-11 01:29

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_product_trademark'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trademark',
            field=models.JSONField(blank=True, default=product.models.trademark_default, help_text='Position value should be pre/post ,if the product has trademark mark display as True '),
        ),
    ]
