# Generated by Django 6.0.2 on 2026-03-18 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_productfaq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfaq',
            old_name='description',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='productfaq',
            old_name='title',
            new_name='question',
        ),
    ]
