# Generated by Django 6.0.2 on 2026-04-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_description_productfaq_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdocument',
            name='tax_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
