# Generated by Django 6.0.2 on 2026-04-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_productdocument_tax_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdocument',
            name='tax_required',
        ),
        migrations.AddField(
            model_name='product',
            name='is_tax_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
