# Generated by Django 6.0.2 on 2026-04-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_is_returnable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_tax_required',
        ),
    ]
