# Generated by Django 6.0.2 on 2026-04-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_product_is_tax_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_shipping_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
