# Generated by Django 6.0.2 on 2026-04-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_create_target_document_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='assaypaneltargetdocument',
            name='target_count',
            field=models.PositiveIntegerField(default=0, help_text='Optional number of targets included in this uploaded list.'),
        ),
        migrations.AddField(
            model_name='productassaydetail',
            name='target_count',
            field=models.PositiveIntegerField(default=0, help_text='Enter the number of assay targets shown on the product card.'),
        ),
    ]
