# Generated by Django 6.0.2 on 2026-04-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_assaypaneltargetdocument_target_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productassaydetail',
            name='catalog_number',
            field=models.CharField(blank=True, help_text='Assay-specific catalog number shown on assay cards.', max_length=100),
        ),
    ]
