# Generated by Django 6.0.2 on 2026-04-20 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_productassaydetail_catalog_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdocument',
            name='extracted_target_text',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='target_search_text',
            field=models.TextField(blank=True, help_text='Optional: paste target/pathogen names for product search.'),
        ),
        migrations.AlterField(
            model_name='assaypaneltargetdocument',
            name='file',
            field=models.FileField(max_length=500, upload_to='assay_target_docs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv'])]),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='file',
            field=models.FileField(db_column='file_url', max_length=500, upload_to='product_docs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv'])]),
        ),
    ]
