# Generated by Django 6.0.2 on 2026-04-21 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_productdocument_extracted_target_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelatedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Accordion header shown to customers.', max_length=255)),
                ('content', models.TextField(help_text='Accordion body. HTML is allowed for formatting.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_information', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Related Information',
                'verbose_name_plural': 'Product Related Informations',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['product', 'is_active', 'sort_order'], name='product_pro_product_6632f6_idx')],
            },
        ),
    ]
