# Generated by Django 6.0.2 on 2026-05-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_productrelatedinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="10 = '10%'", max_digits=10),
        ),
    ]
