# Generated by Django 6.0.2 on 2026-06-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_product_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productassaydetail',
            name='assay_type',
            field=models.CharField(choices=[('respiratory', 'Respiratory'), ('uti', 'UTI (Urinary Tract Infection)'), ('sti', 'STI (Sexually Transmitted Infection)'), ('wound', 'Wound Panel'), ('gi', 'Gastrointestinal'), ('meningitis', 'Meningitis'), ('sepsis', 'Sepsis'), ('other', 'Other'), ('qpcr_qc', 'qPCR Quality Control'), ('semi_quant', 'Semi-Quant Verification Kits'), ('validation_sets', 'Validation Sets'), ('inclusivity_sets', 'Inclusivity Sets')], db_index=True, max_length=30),
        ),
    ]
